name: Build & Deploy Main
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Configure SSH Environment
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          sudo chmod 600 ~/.ssh/id_ed25519
          eval `ssh-agent -s`
          ssh-add ~/.ssh/id_ed25519
          ssh-keyscan -H $SSH_HOST > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.KEY}}
          SSH_HOST: ${{secrets.HOST}}
      - name: Build Docker Image
        run: |
          export HICKSMDE_DIR=/root/hicksmde
          ssh root@${SSH_HOST} \
            -o SendEnv=HICKSMDE_DIR \
            "
              if [ ! -d $HICKSMDE_DIR ]; then
                cd /root
                git clone https://github.com/mwhicks-dev/hicksmde.git
              fi
              cd $HICKSMDE_DIR
              git pull
              docker build --no-cache -t hicksmde .
            "
        shell: bash
        env:
          SSH_HOST: ${{secrets.HOST}}
      - name: Stop Old Docker Container
        run: |
          ssh root@${SSH_HOST} \
            "
              docker stop hicksmde || true
              docker rm hicksmde || true
            "
        shell: bash
        env:
          SSH_HOST: ${{secrets.HOST}}
      - name: Run New Docker Container
        run: |
          export HICKSMDE_DIR=/root/hicksmde
          export CERT_DIR=/root/ssl
          export PYACCT_URI=${PYACCT_URI}
          export AUTHMAIL_URI=${AUTHMAIL_URI}
          ssh root@${SSH_HOST} \
            -o SendEnv=CERT_DIR -o SendEnv=HICKSMDE_DIR \ 
            -o SendEnv=PYACCT_URI -o SendEnv=AUTHMAIL_URI \
            "
              docker run --name hicksmde \
                -e PYACCT_URI=${PYACCT_URI} -e AUTHMAIL_URI=${AUTHMAIL_URI}
                -v /${HICKSMDE_DIR}/config:/hicksmde-mapping/config \
                -v /${CERT_DIR}:/cert/ \
                -p 443:8000 \
                -d --restart=unless-stopped \
                hicksmde --port 8000 --workers 1 \
                --ssl-certfile /cert/fullchain.pem --ssl-keyfile /cert/privkey.pem
            "
        shell: bash
        env:
          SSH_HOST: ${{secrets.HOST}}
          PYACCT_URI: ${{vars.PYACCT_URI}}
          AUTHMAIL_URI: ${{vars.AUTHMAIL_URI}}
          
